import type { Order, Source } from './types';
export const FIXTURE_NOW = '2026-10-01T12:00:00.000Z';
export const orders: Order[] = [
 {id:'PP-1042',accountId:'HH-208',label:'Broken promise',item:'Studio wireless headphones',amount:129,currency:'USD',speaker:'Alex Morgan',recipient:'Alex Morgan',verified:true,region:'US',deliveredAt:'2026-09-29T14:20:00.000Z',status:'Delivered · disputed'},
 {id:'PP-1043',accountId:'HH-309',label:'Existing refund',item:'Everyday backpack',amount:89,currency:'USD',speaker:'Sam Rivera',recipient:'Sam Rivera',verified:true,region:'US',deliveredAt:'2026-09-29T15:00:00.000Z',status:'Delivered · disputed'},
 {id:'PP-1044',accountId:'HH-208',label:'Shared household',item:'Pour-over coffee set',amount:64,currency:'USD',speaker:'Alex Morgan',recipient:'Jordan Morgan',verified:false,region:'US',deliveredAt:'2026-09-30T15:00:00.000Z',status:'Delivered · disputed'},
 {id:'PP-1045',accountId:'HH-410',label:'Insufficient evidence',item:'Desk task light',amount:79,currency:'USD',speaker:'Taylor Lee',recipient:'Taylor Lee',verified:false,region:'CA',deliveredAt:null,status:'Delivery unconfirmed'}
];
function source(id:string,orderId:string|null,type:string,title:string,text:string,timestamp='2026-09-30T09:00:00.000Z',extra:Partial<Source>={}):Source {
 return {id,orderId,accountId:orders.find(o=>o.id===orderId)?.accountId??null,type,title,text,timestamp,version:null,effectiveFrom:null,effectiveTo:null,region:null,photo:null,...extra};
}
export const sources: Source[] = [
 source('SUP-1042-01','PP-1042','support','Yesterday · a commitment was made','Customer Alex Morgan: The app says delivered but I have not received order PP-1042. I was home. I have already checked with my neighbors.\nAgent Maya Chen: Your refund will be initiated within 24 hours.\nCustomer Alex Morgan: Thank you.','2026-09-30T09:00:00.000Z'),
 source('SUP-1042-02','PP-1042','support','Today · third contact','Customer Alex Morgan: Your app says delivered. I was home all day, and nobody came.\nAgent Priya Shah: Have you checked with your neighbors?\nCustomer Alex Morgan: Yes. Yesterday your colleague promised a refund. This is the third time I have explained everything.\nCustomer Alex Morgan: My building has no reception. That photo is not my doorway.','2026-10-01T11:40:00.000Z'),
 source('COU-1042-01','PP-1042','courier','Courier delivery scan','Order PP-1042 marked delivered. Courier note: Left at reception. Photo uploaded. No recipient signature captured.','2026-09-29T14:20:00.000Z',{photo:'/delivery-evidence.svg'}),
 source('SUP-1043-01','PP-1043','support','Refund commitment','Customer Sam Rivera: My order PP-1043 never arrived; I checked with neighbors.\nAgent Maya Chen: Your refund will be initiated within 24 hours.','2026-09-30T09:00:00.000Z'),
 source('COU-1043-01','PP-1043','courier','Delivery note','Order PP-1043 marked delivered. Left at front door. Recipient confirmation unavailable.','2026-09-29T15:00:00.000Z'),
 source('SUP-1044-01','PP-1044','support','Household identity unresolved','Customer Alex Morgan: I am contacting you about order PP-1044 for Jordan. Jordan says the coffee set has not arrived.\nAgent Priya Shah: Are you authorized by Jordan to manage this order?\nCustomer Alex Morgan: I need to check.','2026-10-01T10:00:00.000Z'),
 source('COU-1044-01','PP-1044','courier','Delivery note','Order PP-1044 marked delivered. Parcel left in mailroom. Recipient identity was not recorded.','2026-09-30T15:00:00.000Z'),
 source('SUP-1045-01','PP-1045','support','Missing delivery record','Customer Taylor Lee: My desk light has not arrived. Can you help with order PP-1045?\nAgent Priya Shah: I cannot find a delivery scan or photo.','2026-10-01T11:00:00.000Z'),
 source('CTX-208',null,'account','Shared account context','This is a shared household account. Account access does not establish recipient identity or authority for another person’s order.', '2026-09-01T00:00:00.000Z',{accountId:'HH-208'}),
 source('POL-US-2',null,'policy','US delivery dispute policy','Synthetic policy DNR v2. Applies to US orders on or after 2026-09-01. An agent may approve a simulated refund initiation when: the current speaker is verified as the recipient or authorized representative; a delivery scan and non-receipt complaint exist; at least 24 hours have elapsed since the scan; order value is at most USD 200; and the refund ledger shows no initiation. A previous promise alone does not confer eligibility. Where any prerequisite or applicable policy is missing, escalate to Dispute Review. If initiation already exists, review its status; never initiate twice. Uploaded photos do not establish receipt. Conflicting delivery claims require investigation, not a finding of courier fault.','2026-09-01T00:00:00.000Z',{version:'2.0',effectiveFrom:'2026-09-01T00:00:00.000Z',effectiveTo:null,region:'US'}),
 source('POL-US-1',null,'policy','Retired US policy','Synthetic policy DNR v1. Previously required 48 hours before review. Retired; not applicable on or after 2026-09-01.','2026-01-01T00:00:00.000Z',{version:'1.0',effectiveFrom:'2026-01-01T00:00:00.000Z',effectiveTo:'2026-09-01T00:00:00.000Z',region:'US'})
];
